"""ia2pt.TwoPointModel must reproduce the paper's model code bit-for-bit.

``tests/data/ia2pt_reference_lrg_z1.npz`` was generated by the original
``scripts/ia_model.py`` of the UNIONS x DESI analysis (2026-09-17) at a fixed
parameter set, on the LRG 0.40 < z < 0.75 separation grids and n(z): every
statistic used by the fits (wedged xi~_{0,0}, xi~_{2,2}; eq. 19 w_gg, w_g+),
for NLA and TATT, point values and bin averages, single-z and n(z)-integrated,
with / without the wedge cut, with evolve_bias, and the IA block at z_pair.
"""
from pathlib import Path

import numpy as np
import pytest

from ia2pt import TwoPointModel

REF = Path(__file__).parent / "data" / "ia2pt_reference_lrg_z1.npz"
RTOL = 1e-10


@pytest.fixture(scope="module")
def ref():
    return dict(np.load(REF))


def _pars(ref, cfg):
    return tuple(ref["pars_tatt" if cfg == "TATT" else "pars_nla"])


def _model(ref, cfg, z=None, **kw):
    cosmo = list(ref["cosmology"])
    if z is not None:
        cosmo[-1] = float(z)
    opts = dict(do_rsd=True, pimax=100, rp_min_wedge=5.0, n_mu_wedge=101, bin_avg=False)
    opts.update(kw)
    return TwoPointModel(cosmo, cfg, **opts)


@pytest.mark.parametrize("cfg", ["TATT", "NLA"])
@pytest.mark.parametrize("bin_avg", [False, True])
def test_single_z(ref, cfg, bin_avg):
    m = _model(ref, cfg, bin_avg=bin_avg)
    tag = "ba" if bin_avg else "pt"
    r_s = ref["s_edges"] if bin_avg else ref["s_mid"]
    r_p = ref["rp_edges"] if bin_avg else ref["rp_mid"]
    p = _pars(ref, cfg)
    np.testing.assert_allclose(m.compute_xi_gg_wedge_monopole(r_s, *p), ref[f"{cfg}_{tag}_xi0e"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_xi_gi_wedge_quadrupole(r_s, *p), ref[f"{cfg}_{tag}_xi2p"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_wgg(r_p, *p), ref[f"{cfg}_{tag}_wgg"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_wgp(r_p, *p), ref[f"{cfg}_{tag}_wgp"], rtol=RTOL)


@pytest.mark.parametrize("cfg", ["TATT", "NLA"])
@pytest.mark.parametrize("bin_avg", [False, True])
def test_nz_integrated(ref, cfg, bin_avg):
    m = _model(ref, cfg, bin_avg=bin_avg)
    m.set_nz(ref["z_bins"], ref["z_nz"], ref["nz_clustering"], ref["nz_shape"])
    tag = "ba" if bin_avg else "pt"
    r_s = ref["s_edges"] if bin_avg else ref["s_mid"]
    r_p = ref["rp_edges"] if bin_avg else ref["rp_mid"]
    p = _pars(ref, cfg)
    np.testing.assert_allclose(m.compute_xi_gg_wedge_monopole(r_s, *p), ref[f"{cfg}_{tag}_nz_xi0e"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_xi_gi_wedge_quadrupole(r_s, *p), ref[f"{cfg}_{tag}_nz_xi2p"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_wgg(r_p, *p), ref[f"{cfg}_{tag}_nz_wgg"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_wgp(r_p, *p), ref[f"{cfg}_{tag}_nz_wgp"], rtol=RTOL)


@pytest.mark.parametrize("cfg", ["TATT", "NLA"])
def test_no_wedge_cut_and_evolve_bias(ref, cfg):
    p = _pars(ref, cfg)
    m = _model(ref, cfg, rp_min_wedge=None)
    np.testing.assert_allclose(m.compute_xi_gg_wedge_monopole(ref["s_mid"], *p), ref[f"{cfg}_pt_nocut_xi0e"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_xi_gi_wedge_quadrupole(ref["s_mid"], *p), ref[f"{cfg}_pt_nocut_xi2p"], rtol=RTOL)
    m = _model(ref, cfg, evolve_bias=True)
    np.testing.assert_allclose(m.compute_xi_gg_wedge_monopole(ref["s_mid"], *p), ref[f"{cfg}_pt_evb_xi0e"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_wgp(ref["rp_mid"], *p), ref[f"{cfg}_pt_evb_wgp"], rtol=RTOL)


def test_ia_block_at_pair_redshift(ref):
    m = _model(ref, "NLA", z=ref["z_eff_IA"])
    np.testing.assert_allclose(m.compute_xi_gi_wedge_quadrupole(ref["s_mid"], *_pars(ref, "NLA")),
                               ref["NLA_pt_zia_xi2p"], rtol=RTOL)


def test_parameter_cache_and_sign(ref):
    """Changing a1 must refresh the spectra; positive a1 (radial alignment,
    e_+ = -e_t) gives POSITIVE xi~_{2,2} and w_g+ in this convention."""
    m = _model(ref, "NLA")
    p = list(_pars(ref, "NLA"))
    q2 = m.compute_xi_gi_wedge_quadrupole(ref["s_mid"], *p)
    wgp = m.compute_wgp(ref["rp_mid"], *p)
    assert np.all(q2 > 0) and np.all(wgp > 0)
    p[2] = -p[2]
    np.testing.assert_allclose(m.compute_xi_gi_wedge_quadrupole(ref["s_mid"], *p), -q2, rtol=1e-8)


def test_no_rsd_limits(ref):
    """do_rsd=False -> beta = 0: xi~_{2,2} is the pure xi^{2,2} term."""
    m = _model(ref, "NLA", do_rsd=False)
    p = _pars(ref, "NLA")
    m.compute_xi_gi_wedge_quadrupole(ref["s_mid"], *p)
    assert m._beta(m.f, p[0]) == 0.0
    m_rsd = _model(ref, "NLA")
    q_rsd = m_rsd.compute_xi_gi_wedge_quadrupole(ref["s_mid"], *p)
    q_real = m.compute_xi_gi_wedge_quadrupole(ref["s_mid"], *p)
    # RSD enhance the quadrupole amplitude by ~ (1 + beta/7) at large s
    assert np.all(np.abs(q_rsd[-5:]) > np.abs(q_real[-5:]))


# --------------------------------------------------------------- ++ statistics
REF_PP = Path(__file__).parent / "data" / "ia2pt_reference_pp_lrg_z1.npz"


@pytest.fixture(scope="module")
def ref_pp():
    return dict(np.load(REF_PP))


@pytest.mark.parametrize("cfg", ["TATT", "NLA"])
@pytest.mark.parametrize("bin_avg", [False, True])
@pytest.mark.parametrize("nz", [False, True])
def test_pp_statistics(ref, ref_pp, cfg, bin_avg, nz):
    """Characterisation fixture (tests/make_reference_pp.py) of the shape-shape
    statistics: xi~_{0,0}^{++}, xi~_{4,4}^{++}, w_++, w_xx."""
    m = _model(ref, cfg, bin_avg=bin_avg)
    if nz:
        m.set_nz(ref["z_bins"], ref["z_nz"], ref["nz_clustering"], ref["nz_shape"])
    tag = "ba" if bin_avg else "pt"
    k = f"{cfg}_{tag}_{'nz' if nz else 'z'}"
    r_s = ref["s_edges"] if bin_avg else ref["s_mid"]
    r_p = ref["rp_edges"] if bin_avg else ref["rp_mid"]
    p = _pars(ref, cfg)
    np.testing.assert_allclose(m.compute_xi_pp_wedge_monopole(r_s, *p), ref_pp[f"{k}_xi0pp"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_xi_pp_wedge_hexadecapole(r_s, *p), ref_pp[f"{k}_xi4pp"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_wpp(r_p, *p), ref_pp[f"{k}_wpp"], rtol=RTOL)
    np.testing.assert_allclose(m.compute_wxx(r_p, *p), ref_pp[f"{k}_wxx"], rtol=RTOL)


@pytest.mark.parametrize("cfg", ["TATT", "NLA"])
def test_pp_limber_limit(ref, cfg):
    """Physics check of the ++ multipole expansion: for Pi_max -> infinity the
    eq. 19 projection of the xi_++ multipoles must reduce to the Limber form
    w_++ = (1/2pi) Int k dk [P_A J_0 + P_B J_4] (P_A = (P_EE + P_BB)/2,
    P_B = (P_EE - P_BB)/2), w_xx the same with P_B -> -P_B. TATT has P_BB != 0
    so it also tests the E/B split. The 3e-3 tolerance is the numerical floor
    of the eq. 19 route against the 2D fftlog (the w_gg path shows the same)."""
    from fastpt.misc import HT
    from scipy.interpolate import CubicSpline

    m = _model(ref, cfg, pimax=3000, dpi=0.25, rp_min_wedge=0)
    p = _pars(ref, cfg)
    rp = np.geomspace(1.0, 60.0, 12)
    wpp, wxx = m.compute_wpp(rp, *p), m.compute_wxx(rp, *p)
    pk_ee, pk_bb = m._pk_ii()
    a = 1.0 / (1.0 + m.zeff)
    P_EE = m.h**3 * pk_ee(m.ks, a, m.cosmo)
    P_BB = m.h**3 * pk_bb(m.ks, a, m.cosmo)
    r, w0 = HT.k_to_r(m.k, 0.5 * (P_EE + P_BB), 1.0, -1.0, 0.0, 1.0 / (2 * np.pi))
    _, w4 = HT.k_to_r(m.k, 0.5 * (P_EE - P_BB), 1.0, -1.0, 4.0, 1.0 / (2 * np.pi))
    w0, w4 = CubicSpline(r, w0)(rp), CubicSpline(r, w4)(rp)
    if cfg == "TATT":
        assert np.max(P_BB / P_EE) > 0.05
    np.testing.assert_allclose(wpp, w0 + w4, rtol=3e-3)
    # w_xx crosses zero: absolute tolerance scaled by w_++
    np.testing.assert_allclose(wxx, w0 - w4, atol=3e-3 * np.abs(wpp).max())
